spring:
  application:
    name: food-ordering
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: feastora
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: ${PORT:9091}

jwt:
  secret-key: ${SECRET_SUPER_KEY}


