spring:
  application:
    name: food-ordering
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: feastora
  security:
    user:
      name: admin
      password: admin@321

server:
  port: ${PORT:9091}

jwt:
  secret-key: ${SECRET_SUPER_KEY}